name: cicd pipeline

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
        
    workflow_dispatch:
        
        inputs:
            environments:
                description: 'select the environment to deploy'
                required: true
                default: 'staging'
                type: choice
                options:
                    - staging
                    - production

concurrency:
    group: ${{github.workflow}}-${{github.ref}} 
    cancel-in-progress: true
    
env:
    NODE_VERSION: "20.x"
    POSTGRES_VERSION: "16"
    DOCKER_REGISTERY: ghcr.io
    IMAGE_NAME: ${{github.repository}} 
    SONAR_PROJECT_KEY: ${{github.repository_owner}}-${{github.event.repository.name}}
    
jobs:
    code_quality:
        name: "Code Quality"
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: setup pnpm
              uses: pnpm/action-setup@v3
              with:
                version: 10

            - name: setup node${{env.NODE_VERSION}}
              uses: actions/setup-node@v4
              with:
                node-version: ${{env.NODE_VERSION}}
                cache: "pnpm"
                cache-dependency-path: |
                 client/pnpm-lock.yml
                 server/pnpm-lock.yml

            - name: instaall frontend dependency
              working-directory: ./client
              run: pnpm install --frozen-lockfile
              
            - name: instaall backend dependency
              working-directory: ./server
              run: pnpm install --frozen-lockfile

            - name: client lint
              working-directory: ./client
              run: |
                pnpm run lint  --max-warnings=0
                pnpm run format:check
                
            - name: server lint
              working-directory: ./server
              run: |
                pnpm run lint  --max-warnings=0
                pnpm run format:check

            - name: typescript type check -client
              working-directory: ./client
              run: pnpm run type-check
              
              
            - name: typescript type check -server
              working-directory: ./server
              run: pnpm run type-check

            
              
    dependency_audit:
        name: "Dependency Audit"
        runs-on: ubuntu-latest

        steps: 
            - name: chekout code   
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: setup node${{env.NODE_VERSION}}
              uses: actions/setup-node@v4
              with:
                node-version: ${{env.NODE_VERSION}}
                cache: "pnpm"

            - name: audit client dependency
              working-directory: ./client
              run: pnpm audit --audit-level=High

            - name: audit server dependency
              working-directory: ./server
              run: pnpm audit --audit-level=High

   
            - name: Run snyk security scan
              uses: snyk/actions/node@master
              continue-on-error: true
              with:
                args: --severity-threshold=high  --all-projects --sarif-file-output=snyk.sarif

            - name: upload snyk result on github security
              uses: github/codeql-action/upload-sarif@v3    
              if: always()
              with:
                sarif_file: snyk.sarif
              continue-on-error: true


    security_scan:
        name: "Security Scan"
        runs-on: ubuntu-latest

        steps:
          - name: checkout code
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          - name: Run truffleHog secret detection
            uses: trufflesecurity/trufflehog@main
            with:
              base: ${{github.event.repository.default_branch}}
              head: HEAD
              extra_args: --fail


    sast_codeQl:
      name: "SAST CodeQl Analisis"
      runs-on: ubuntu-latest
      permissions:
        actions: read
        contents: read
        security-events: write

      strategy:
        matrix:
          languages: [javascript, typescript]  
        
      steps:
        - name: checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0


        - name: initilize CodeQl
          uses: github/codeql-action/init@v3
          with:
            languages: ${{matrix.languages}}
            queries: security-extended, security-and-quality
            
        - name: Autobuild
          uses: github/codeql-action/autobuild@v3
          
          
        - name: perform codeql analysis
          uses: github/codeql-action/analyze@v3
          with:
            category: "/languages:${{matrix.languages}}"  
          

    test_server:
      name: "server test (jest+ supertest)"
      runs-on: ubuntu-latest
      needs: [code_quality] 

      services:
        postgres:
          image: postgres:16-alpine
          env:
            POSTGRES_PASSWORD: test_password
            POSTGRES_USER: test_user
            POSTGRES_DB: test_db
          ports:
            - "5432:5432"
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
  
        redis:
          image: redis:7-alpine
          ports:
            - "6379:6379"
          options: >-
            --health-cmd "redis-cli ping"
            --health-intrval 10s 
            --health-timeout 5s
            --health-retries 5
      env:
        NODE_ENV: test
        DATABASE_URL: postgres://test_user:test_password@postgres:5432/test_db
        REDIS_URL: redis://redis:6379
        JWT_SECRET: test_jwtsecret_for_ci
        JWT_REFRESH_SECRET: test_jwtrefreshsecret_for_ci
        

      steps:
        - name: checkout code
          uses: actions/checkout@v4
          with: 
            fetch-depth: 0
            
        - name: setup pnpm
          uses: pnpm/action-setup@v3
          with:
            version: 10
            
        - name: setup node
          uses: actions/setup-node@v4
          with: 
            node-version: ${{env.NODE_VERSION}}
            cache: "pnpm"
            cache-dependency-path: |
              server/pnpm-lock.yml

        - name: install dependency
          working-directory: ./server
          run: pnpm install --frozen-lockfile
          

        - name: Run db migration
          working-directory: ./server
          run: pnpm run db:migrate 
          
        - name: Run db seed (test data)
          working-directory: ./server
          run: pnpm run db:seed:test
          
        - name: Run unit test with coverage
          working-directory: ./server
          run: pnpm run test:unit -- --coverage coverageReporters=lcov,text,clover

        - name: Integrating testing
          working-directory: ./server
          run: pnpm run test:integration
          
        - name: upload coverage report
          uses: codecov/codecov-action@v4
          with:
            token: ${{secrets.CODECOV_TOKEN}}
            directory: ./server/coverage
            flags: server
            fail_ci_if_error: true

        - name: Assert coverage threadshold
          working-directory: ./server
          run: pnpm run test:coverage-chek     

    test-client:
      name: "Client test (vitest + RTL)"
      runs-on: ubuntu-latest
      

      steps:
        - name: checkout code
          uses: actions/checkout@v4
          with: 
            fetch-depth: 0
            
        - name: setup pnpm
          uses: pnpm/action-setup@v3
          with:
            version: 10
            
        - name: setup node
          uses: actions/setup-node@v4
          with:
            node-version: ${{env.NODE_VERSION}} 
            cache: "pnpm"
            
        - name: Install dependicies
          working-directory: ./client
          run: pnpm install --frozen-lockfile
          
        - name: Run unit and component test
          working-directory: ./client
          run: pnpm run test -- --coverage  
  
        - name: upload coverage repot
          uses: codecov/codecov-action@v4
          with: 
            token: ${{secrets.CODE_COV}}
            working-directory: ./client/coverage
            flags: client
            fail_ci_if_error: true
            
    sonarCloud:
      name: "sonarcloud analysis "
      runs-on: ubuntu-latest        

      steps: 
        - name: checkout code
          uses: actions/checkout@v4
          with: 
            fetch-depth: 0
            
        - name: sonarcloud action
          uses: SonarSource/sonarcloud-github-action@v3
          env:
            SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
          with: 
            args: >  
              -Dsonar.projectKey= ${{env.SONAR_PROJECT_KEY}}
              -Dsonar.organization= ${{github.repository_owner}}
              -Dsonar.sources= client/src, server/src
              -Dsonar.tests= client/src, server/src
              -Dsonar.test.inclusions=**/*.test.ts, **/*.test.tsx, **/*.spec.ts
              -Dsonar.javascript.lcov.reportPaths=client/coverage/lcov.info, server/coverage/lcov.info
              -Dsonar.qualitygate.wait=true
           
  
   
        
      
            
              
